name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: [OfficialGaming]
depend:
  - Votifier
  - VulcanLib
softdepend: [PlaceholderAPI]
commands:
  vote:
    description: vote cmd
    aliases: [vulcanvote]
